sudo: required
dist: trusty
language: cpp
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
install:
  - sudo apt-get install cmake
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - ./build.sh
  
  
